export const SWAP_CURRENCY = 'SWAP_CURRENCY';
export const SET_CURRENT_CURRENCY = 'SET_CURRENT_CURRENCY';
export const CHANGE_CUR_AMOUNT = 'CHANGE_CUR-AMOUNT';
export const SWITCH_THEME = 'SWITCH_THEME';
