export const SWAP_CURRENCY = 'SWAP_CURRENCY';
export const SET_BASE_CURRENCY = 'SET_BASE_CURRENCY';
export const SET_QUOTE_CURRENCY = 'SET_QUOTE_CURRENCY';
export const CHANGE_CUR_AMOUNT = 'CHANGE_CUR-AMOUNT';
export const GET_INITIAL_CONVERSION = 'GET_INITIAL_CONVERSION';
export const SWITCH_THEME = 'SWITCH_THEME';
